name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: update plugins
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        pass: ${{ secrets.PASSWORD }}
        last_ssh: |
          cd /home/repository/GroupBot
          git pull
